### ISSUE TITLE
Backend - Build Web API

### ISSUE THREAD

**Issue by rkkakar** [manleydrake/ML_Bets#11]
As a developer, I want a baseline back-end environment that can support scalability based on environment variables.

**Comment by JHill6253** [comment]
Acceptance Criteria:
* Postman CRUD application 
* Visible implementation into .Net app

**Comment by JHill6253** [comment]
API needs to connect to NBA Stats website

**Comment by JHill6253** [comment]
In last commit to JohnAPIBranch I have completed a call to a dummy .NET API to render on the React Application. Will continue to build out API tonight hopefully adding a controller to display changes on Stats page. Considering creating a middleware so there is no need to create multiple API's

**Comment by JTHxDev** [comment]
Completed
