### ISSUE TITLE
NBA Stats Web Scrapping 

### ISSUE THREAD

**Issue by JHill6253** [manleydrake/ML_Bets#8]
As a developer working on the ML side, I need to have access to a database that contains the required data points to train my ML algorithm.

Key achievements:
- Find web scrapper 
- Determine columns/Data to pull in
- Clean Data/Transform into table

**Comment by mitushiananya** [comment]
You can make use of the official [NBA Website](https://www.nba.com/stats/) to extract data. And there is another website called [Basketball Reference](https://www.basketball-reference.com/), you can scrape or directly download player data, team data, historical data etc. The web-page [five thirty eight](https://projects.fivethirtyeight.com/2021-nba-predictions/) contains data about the 2020-2021 NBA predictions.

**Comment by JTHxDev** [comment]
Completed
